mkdir -p "{$PREFIX}/share/app/{jars,libs,config,genome/index}"
cp metadata/jars/jcna-biomrkrs-final_11.jar "{$PREFIX}/share/app/jars/"
cp metadata/jars/libs/all-libraries.jar "{$PREFIX}/share/app/libs/"
cp metadata/jars/libs/zstd-jni-1.5.7-4-linux_amd64.jar "{$PREFIX}/share/app/libs/"
cp metadata/scripts/run_pipeline_module2to6.sh "{$PREFIX}/share/app/"
cp metadata/scripts/reads_preprocessing.sh "{$PREFIX}/share/app/"
cp metadata/config/log4j2.xml "{$PREFIX}/share/app/config/"
wget -P "{$PREFIX}/share/app/" https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr22.fa.gz
gunzip "{$PREFIX}/share/app/chr22.fa.gz"
bowtie2-build "{$PREFIX}/share/app/chr22.fa" "{$PREFIX}/share/app/genome/index"
