FROM ubuntu:latest

ENV OS_TYPE=linux-64    

WORKDIR /app
COPY python /app/python
COPY scripts/run_pipeline_module1.sh /app/
COPY scripts/run_pipeline_module2to6.sh /app/

# Install system dependencies
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    curl \
    wget \
    ca-certificates \
    vim \
    unzip \
    openjdk-21-jdk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && \
    bash miniconda.sh -b -p /opt/conda && \
    rm miniconda.sh

ENV PATH=/opt/conda/bin:$PATH

# Create environment with bio packages
RUN conda install -y -c bioconda -c conda-forge \
    fastqc trimmomatic bowtie2 samtools multiqc &&\
    conda clean -afy && \
    rm -rf ~/.conda

ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64/
ENV PATH=$JAVA_HOME/bin:$PATH

# Make both scripts executable
RUN chmod +x /app/run_pipeline_module1.sh /app/run_pipeline_module2to6.sh

# Default entry point to bash for flexibility
ENTRYPOINT ["bash"]
