FROM ubuntu:latest

ENV OS_TYPE=linux-64    

WORKDIR /app

# Install system dependencies
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    wget \
    ca-certificates \
    openjdk-21-jdk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Miniforge
RUN wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O miniforge.sh && \
    bash miniforge.sh -b -p /opt/conda && \
    rm miniforge.sh

ENV PATH=/opt/conda/bin:$PATH

# Create environment with bio packages
RUN conda install -y -c bioconda -c conda-forge fastqc trimmomatic bowtie2 samtools picard multiqc &&\
    conda clean -afy && \
    rm -rf ~/.conda

ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64/
ENV PATH=$JAVA_HOME/bin:$PATH

# Use bash as default shell for all RUN/CMD/ENTRYPOINT
SHELL ["/bin/bash", "-c"]

# Default entrypoint
CMD ["/bin/bash"]

