FROM ubuntu:latest

ENV OS_TYPE=linux-64
ARG MICROMAMBA_VERSION=1.4.4

WORKDIR /app
COPY wdr/ /app/

# Install system dependencies
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    bzip2 \
    curl \
    wget \
    ca-certificates \
    x11-apps \
    xauth \
    xserver-xorg-video-dummy \
    vim \
    unzip \
    openjdk-21-jdk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && \
    bash miniconda.sh -b -p /opt/conda && \
    rm miniconda.sh

ENV PATH=/opt/conda/bin:$PATH

# Create environment with bio packages
RUN conda install -y -c bioconda -c conda-forge \
    fastqc trimmomatic bowtie2 samtools picard && \
    conda clean -afy

#ENV CONDA_PREFIX=/opt/conda/envs/base
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64/
#ENV PATH=${CONDA_PREFIX}/bin:${JAVA_HOME}/bin:${PATH}
ENV PATH=$JAVA_HOME/bin:$PATH

#ENTRYPOINT ["bash", "/app/sequencing/bash_scripts/reads_prep_NCBI_H_filtered_max600_test.sh"]
ENTRYPOINT ["java", "-jar", "/app/ssearchBiomarkers.jar"]


